http:
 #region routers 
  routers:
    omada:
      entryPoints:
        - "https"
      rule: "Host(`omada.comprofix.xyz`)"
      middlewares:
        - mid-omada-headers
      tls: {}
      service: omada
    
    gitlab:
      entryPoints:
        - "https"
      rule: "Host(`git.comprofix.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: gitlab

    registry.gitlab:
      entryPoints:
        - "https"
      rule: "Host(`registry.git.comprofix.com`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: gitlab

  services: 
    omada:
      loadBalancer:
        servers:
          - url: "https://omada-server.comprofix.xyz:8043/"
        passHostHeader: true
    gitlab:
      loadBalancer:
        servers:
          - url: "https://10.10.10.7"
        passHostHeader: true
    

    registry.gitlab:
      loadBalancer:
        servers:
          - url: "https://10.10.10.7"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    mid-omada-headers:
      headers:
        customRequestHeaders:
          host: "omada.comprofix.xyz"
        customResponseHeaders:
          host: "omada.comprofix.xyz"

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers