stages:
  - deploy

deploy:
  stage: deploy
  image: debian:12 # Use a base image with Python installed
  services:
    - docker:dind # Enable Docker service for running Docker commands within GitLab CI/CD
  script:
    - apt-get update && apt-get install -y git # Install Git
    - |
      echo "CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME"
      echo "CI_COMMIT_BEFORE_SHA: $CI_COMMIT_BEFORE_SHA"
      echo "CI_COMMIT_SHA: $CI_COMMIT_SHA"
      # Check if git diff command fails and exit if it does
      if ! changed_tasks=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep "^ansible/tasks/.*\.yml$"); then
        echo "Error: Failed to run git diff command"
        exit 1
      fi
      if [ -n "$changed_tasks" ]; then
        # Split the changed tasks into an array and iterate over them
        IFS=$'\n' read -r -d '' -a tasks_array <<< "$changed_tasks"
        for task in "${tasks_array[@]}"; do
          echo "The following task file has been updated: $task"
          echo "Running Ansible playbook for $task..."
          # Add your Ansible playbook execution command here for each task
        done
      else
        echo "No changes detected in task files. Skipping Ansible playbook execution."
      fi
  only:
    - master