stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest # Use a base image with Python installed
  before_script:
    - apk update
    - apk add --no-cache git openssh ansible
    - mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
  script:
  #services:
  #  - docker:dind # Enable Docker service for running Docker commands within GitLab CI/CD
  script:
    - |
      if changed_tasks=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep "^ansible/tasks/.*\.yml$"); then
        updated_task=$(echo "$changed_tasks" | head -n 1)  
        echo "The following task file has been updated: $updated_task"
        echo "Running Ansible playbook..."
        basename=$(basename $updated_task)
        tags=${basename%.*}_install
        chmod 700 ansible
        ssh -oStrictHostKeyChecking=no -T root@vps01.comprofix.com
        #cd ansible
        #ansible-playbook deploy-homelab.yml --tags $tags
      else
         echo "No changes detected in task files. Skipping Ansible playbook execution."
      fi

  only:
    - master
