stages:
  - deploy

deploy:
  stage: deploy
  image: python:3.12-slim # Use a base image with Python installed
  services:
    - docker:dind # Enable Docker service for running Docker commands within GitLab CI/CD
  variables:
    DOCKER_DRIVER: overlay2 # Set Docker driver to overlay2
  script:
    - apt-get update && apt-get install -y git # Install Git
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
        changed_tasks=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA | grep "^ansible/tasks/.*\.yml$")
        
        if [[ -n "$changed_tasks" ]]; then
          # Extract the filename of the first modified task file
          updated_task=$(echo "$changed_tasks" | head -n 1)
          
          echo "The following task file has been updated: $updated_task"
          echo "Running Ansible playbook..."
          echo $updated_task
        else
          echo "No changes detected in task files. Skipping Ansible playbook execution."
        fi
      else
        echo "Not on the master branch. Skipping Ansible playbook execution."
        
      fi
