stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest # Use a base image with Python installed
  before_script:
    - apk update
    - apk add --no-cache git openssh ansible bash
    - ln -sf /bin/bash /bin/sh
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - echo "HOST *" > ~/.ssh/config
    - echo "StrictHostKeyChecking no" >> ~/.ssh/config
  script:
    - echo "$ANSIBLE_VAULT_PASSWORD" > .vault_password.txt
    - ./ansible/scripts/deploy.sh $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA 
  only:
    - master