---
  
- name: Install NFS mount utility
  ansible.builtin.apt:
    update_cache: true
    pkg: nfs-common
    state: present
  when: ansible_os_family == "Debian"

- name: Mount an NFS volume - {{ nfs_source }}
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    state: "{{ item.state | default( 'mounted' ) }}"
    fstype: nfs
  with_items:
    - name: Docker share
      path: /mnt/nfs/docker
      src: truenas.comprofix.xyz:/mnt/datapool/docker
    - name: Data share
      path: /mnt/nfs/data
      src: truenas.comprofix.xyz:/mnt/datapool/data


