name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Prepare Build
    runs-on: alpine-latest
    container: alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache ansible nodejs npm git bash openssh
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          echo "HOST *" > ~/.ssh/config
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
         
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Deploy containers
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_password.txt
          ./ansible/scripts/deploy.sh "${{ github.event.before }}" "${{ github.sha }}"

          