name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Prepare Build
    runs-on: alpine-latest
    container: alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache ansible nodejs npm git
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deployment script
        shell: bash
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > ~/.vault_password.txt
          ./ansible/scripts/deploy.sh ${{ github.event.before }} ${{ github.sha }}
          