name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Prepare Build
    runs-on: alpine-latest
    container: alpine-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4