name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Prepare Build
    runs-on: alpine-latest
    container: alpine:latest
    steps:
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache ansible nodejs npm
          
      - name: Checkout code
        uses: actions/checkout@v4