---
- name: Set Facts
  set_fact:
    container_name: 'codeserver'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"

- name: Create the {{container_name}} container
  docker_container:
    name: codeserver
    image: ghcr.io/linuxserver/code-server:4.90.3
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /mnt/nfs/docker/codeserver/config:/config
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: codeserver.comprofix.xyz
    port: 8443
    protocol: http
  notify: 
    - reload nginx