---
- name: Set Facts
  set_fact:
    container_name: 'dozzle'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"

- name: Create the {{container_name}} container
  docker_container:
    name: dozzle
    image: amir20/dozzle:v7.0.5
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      DOZZLE_LEVEL: "trace"
      DOZZLE_REMOTE_HOST: "tcp://docker.comprofix.xyz:2375,tcp://omada-server.comprofix.xyz:2375"

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: dozzle.comprofix.xyz
    port: 8080
    protocol: http

- name: Restart nginx
  community.docker.docker_container_exec:
    container: nginx
    command: nginx -s reload
  