---
- name: Set Facts
  set_fact:
    container_name: 'gitlab-runner'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"

- name: Create the {{container_name}} container
  docker_container:
    name: gitlab-runner
    image: gitlab/gitlab-runner:alpine-v17.0.0
    restart_policy: always
    recreate: true
    networks:
      - name: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ docker_configs }}/{{container_name}}/config:/etc/gitlab-runner"

- name: Register Runner
  community.docker.docker_container_exec:
    container: gitlab-runner
    command: gitlab-runner register --non-interactive --executor=docker --url={{ GITLAB_URL }} --token={{ GITLAB_RUNNER_TOKEN }} --docker-image=alpine:latest
    



    