---
- name: Set Facts
  set_fact:
    container_name: 'homepage'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"

- name: Create the {{container_name}} container
  docker_container:
    name: homepage
    image: ghcr.io/gethomepage/homepage:v0.9.2
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      LOG_LEVEL: debug
    volumes:
      - /mnt/nfs/docker/homepage/config:/app/config 
      - /opt/dashboard-icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    
- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: homepage.comprofix.xyz
    port: 3000
    protocol: http
  notify: 
    - reload nginx
