---
- name: Set Facts
  set_fact:
    container_name: 'jellyseerr'
    
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: jellyseerr
    image: fallenbagel/jellyseerr:1.9.2 
    restart_policy: never
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    volumes:
      - /mnt/nfs/docker/jellyseerr/config:/app/config 

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: jellyseerr.comprofix.xyz
    port: 5055
    protocol: http
  notify: 
    - reload nginx