---
- name: Set Facts
  set_fact:
    container_name: 'jellyfin'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"

- name: Create the {{container_name}} container
  docker_container:
    name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:10.9.6
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /mnt/nfs/docker/jellyfin/config:/config
      - /mnt/nfs/data:/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: jellyfin.comprofix.xyz
    port: 8096
    protocol: http

- name: Restart nginx
  community.docker.docker_container_exec:
    container: nginx
    command: nginx -s reload