---
- name: Set Facts
  set_fact:
    container_name: 'lidarr'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/lidarr"
    - "/mnt/nfs/docker/lidarr/config"
  
- name: Create the lidarr container
  docker_container:
    name: lidarr
    image: ghcr.io/linuxserver/lidarr:latest@sha256:e504ab630ab456a4a39a6801f760975ff84fe53a0e542439d80aa8da27773a6e
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:lidarr"
    volumes:
      - /mnt/nfs/docker/lidarr/config:/config
      - /mnt/nfs/data:/data
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/lidarr.conf"
  vars:
    domain: "{{ 'lidarr.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'lidarr.comprofix.xyz' }}"
    port: 8686
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx