---
- name: Set Facts
  set_fact:
    container_name: 'mariadb'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/mariadb"
    - "/mnt/nfs/docker/mariadb/config"
  
- name: Create the mariadb container
  docker_container:
    name: "mariadb"
    image: ghcr.io/linuxserver/mariadb:10.11.8
    restart_policy: no
    recreate: true
    ports:
      - 3306:3306
    env:
      PUID: "0"
      PGID: "0"
      MYSQL_ROOT_PASSWORD: "{{MYSQL_ROOT_PASSWORD}}"
      TZ: "Australia/Brisbane"
    volumes:
      - "/mnt/nfs/docker/mariadb/config:/config"
    