---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/mealie"
    - "/mnt/nfs/docker/mealie/config"

- name: Create the mealie container
  docker_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:v1.11.0
    restart_policy: no
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "false"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "true"
      RECIPE_DISABLE_AMOUNT: "true"
      BASE_URL: "{{ 'mealie.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'mealie.comprofix.xyz' }}"
      SMTP_HOST: comprofix-com.mail.protection.outlook.com
    volumes:
      - /mnt/nfs/docker/mealie/data/:/app/data
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/mealie.conf"
  vars:
    domain: "{{ 'mealie.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'mealie.comprofix.xyz' }}"
    port: 9000
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx