---
- name: Set Facts
  set_fact:
    container_name: 'mealie'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"

- name: Create the {{container_name}} container
  docker_container:
    name: mealie
    image: ghcr.io/mealie-recipes/mealie:v1.8.0
    restart_policy: always
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      RECIPE_PUBLIC: "true"
      RECIPE_SHOW_NUTRITION: "false"
      RECIPE_SHOW_ASSETS: "true"
      RECIPE_LANDSCAPE_VIEW: "true"
      RECIPE_DISABLE_COMMENTS: "true"
      RECIPE_DISABLE_AMOUNT: "true"
      BASE_URL: https://mealie.comprofix.xyz
      SMTP_HOST: comprofix-com.mail.protection.outlook.com
    volumes:
      - /mnt/nfs/docker/mealie/data/:/app/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: mealie.comprofix.xyz
    port: 9000
    protocol: http

- name: Restart nginx
  community.docker.docker_container_exec:
    container: nginx
    command: nginx -s reload