---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/opengist"
    - "/mnt/nfs/docker/opengist/config"

- name: Create the opengist container
  docker_container:
    name: opengist
    image: ghcr.io/thomiceli/opengist:1.7
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - "/mnt/nfs/docker/opengist:/opengist"
    env:
      OG_GITEA_CLIENT_KEY: "{{ OG_GITEA_KEY }}"
      OG_GITEA_SECRET: "{{ OG_GITEA_SECRET }}"
      # URL of the Gitea instance. Default: https://gitea.com/
      OG_GITEA_URL: "https://gitea.comprofix.com"
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/opengist.conf"
  vars:
    domain: "{{ 'gist.dev.comprofix.com' if inventory_hostname == 'dev.comprofix.xyz' else 'gist.comprofix.com' }}"
    port: 6157
    protocol: http
    cert: "{{ 'dev.comprofix.com' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.com' }}"
  notify: 
    - reload nginx
