---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/osticket"
    - "/mnt/nfs/docker/osticket/config"

- name: Create the osticket container
  docker_container:
    name: osticket
    image: devinsolutions/osticket:1.17.5
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      SMTP_HOST: comprofix-com.mail.protection.outlook.com
      MYSQL_HOST: "{{MYSQL_HOST}}"
      MYSQL_DATABASE: "{{OST_DATABASE}}"
      MYSQL_USER: "{{OST_DB_USER}}"
      MYSQL_PASSWORD: "{{OST_DB_PASSWORD}}"
      INSTALL_SECRET: "{{OST_SIRI}}"
  register: container

- name: Add tzdata to osTicket container
  community.docker.docker_container_exec:
    container: osticket
    command: apk add tzdata
  
- name: Set container Timezone
  community.docker.docker_container_exec:
    container: osticket
    command: "ln -s /usr/share/zoneinfo/Australia/Brisbane /etc/localtime"

- name: Set PHP Timezone
  community.docker.docker_container_exec:
    container: osticket
    command: "sed -i 's|UTC|Australia/Brisbane|g' /usr/local/etc/php/conf.d/php-osticket.ini"

- name: Patch mysqli.php for timezone
  community.docker.docker_container_exec:
    container: osticket
    command: "sed -i 's|system_time_zone|time_zone|g' /var/www/html/include/mysqli.php"

- name: Clear ost_sessions table
  mysql_query:
    login_host: "{{MYSQL_HOST}}"
    login_user: "{{OST_DB_USER}}"
    login_password: "{{OST_DB_PASSWORD}}"
    login_db: "{{OST_DATABASE}}"
    query: 
      - USE comprofix_ost; 
      - TRUNCATE TABLE ost_session;

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/osticket.conf"
  vars:
    domain: "{{ 'helpdesk.dev.comprofix.com' if inventory_hostname == 'dev.comprofix.xyz' else 'helpdesk.comprofix.com' }}"
    port: 80
    protocol: http
    cert: "{{ 'dev.comprofix.com' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.com' }}"
  notify: 
    - reload nginx
