---
- name: Set Facts
  set_fact:
    container_name: 'planka'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: planka
    image: ghcr.io/plankanban/planka:1.17.4
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    env:
      BASE_URL: "https://planka.comprofix.xyz"
      DATABASE_URL: "postgresql://{{PLANKA_USER}}:{{PLANKA_PASS}}@docker.comprofix.xyz/planka"
      SECRET_KEY: "{{PLANKA_SECRET_KEY}}"
    volumes:
      - /mnt/nfs/docker/planka/user-avatars:/app/public/user-avatars
      - /mnt/nfs/docker/planka/project-background-images:/app/public/project-background-images
      - /mnt/nfs/docker/planka/attachments:/app/public/attachments
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare


