---
- name: Set Facts
  set_fact:
    container_name: 'portainer'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:2.20.3
    restart_policy: never
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs/docker/portainer/data:/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: portainer.comprofix.xyz
    port: 9443
    protocol: https
  notify: 
    - reload nginx