---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/portainer"
    - "/mnt/nfs/docker/portainer/config"
  
- name: Create the portainer container
  docker_container:
    name: portainer
    image: portainer/portainer-ce:2.20.3
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/nfs/docker/portainer/data:/data
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/portainer.conf"
  vars:
    domain: "{{ 'portainer.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'portainer.comprofix.xyz' }}"
    port: 9443
    protocol: https
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx