---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/privatebin"
    - "/mnt/nfs/docker/privatebin/data"

- name: Create the privatebin container
  docker_container:
    name: privatebin
    image: ghcr.io/privatebin/nginx-fpm-alpine:latest@sha256:7f62871686eb9107ffe7166b7667883c0355e454264bab24246397adc358b261
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /mnt/nfs/docker/privatebin/data:/srv/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/privatebin.conf"
  vars:
    domain: "{{ 'privatebin.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'privatebin.comprofix.xyz' }}"
    port: 8080
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx
