---
- name: Set Facts
  set_fact:
    container_name: 'privatebin'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}/data"

- name: Create the {{container_name}} container
  docker_container:
    name: privatebin
    image: ghcr.io/privatebin/nginx-fpm-alpine:latest@sha256:1c578b1d1642fd6ce44c80faf340fcf6ed414a527993149f8e26c2353fb3230d
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /mnt/nfs/docker/privatebin/data:/srv/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: privatebin.comprofix.xyz
    port: 8080
    protocol: http

- name: Restart nginx
  community.docker.docker_container_exec:
    container: nginx
    command: nginx -s reload