---
- name: Set Facts
  set_fact:
    container_name: 'privatebin'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}/data"

- name: Create the {{container_name}} container
  docker_container:
    name: privatebin
    image: ghcr.io/privatebin/nginx-fpm-alpine:latest@sha256:08d1476a959479dd49a8c1a9ebeb27342f2d93ccf2c620eb30a2c6f6123a0d6b
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /mnt/nfs/docker/privatebin/data:/srv/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: privatebin.comprofix.xyz
    port: 8080
    protocol: http
  notify: 
    - reload nginx