---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/privatebin"
    - "/mnt/nfs/docker/privatebin/data"

- name: Create the privatebin container
  docker_container:
    name: privatebin
    image: ghcr.io/privatebin/nginx-fpm-alpine:latest@sha256:785975dca20a13d7dde5309fd2f25989d432dc0e299e641d638321a4d7da7cb3
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    volumes:
      - /mnt/nfs/docker/privatebin/data:/srv/data
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/privatebin.conf"
  vars:
    domain: "{{ 'privatebin.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'privatebin.comprofix.xyz' }}"
    port: 8080
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx
