---
- name: Set Facts
  set_fact:
    container_name: 'prowlarr'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: prowlarr
    image: linuxserver/prowlarr:1.19.0
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:prowlarr"
    volumes:
      - /mnt/nfs/docker/prowlarr/config:/config

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: prowlarr.comprofix.xyz
    port: 9696
    protocol: http
  notify: 
    - reload nginx