---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/pykms"
    - "/mnt/nfs/docker/pykms/config"
  
- name: Create the pykms container
  docker_container:
    name: pykms
    image: ghcr.io/py-kms-organization/py-kms:latest
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    ports:
      - "1688:1688"
    env:
      IP: "0.0.0.0"
      SQLITE: "true"
      HWID: "RANDOM"
      LOGLEVEL: "INFO"
    volumes:
      - /mnt/nfs/docker/pykms/db:/home/py-kms/db
      - /etc/localtime:/etc/localtime:ro

