---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/radarr"
    - "/mnt/nfs/docker/radarr/config"
  
- name: Create the radarr container
  docker_container:
    name: radarr
    image: linuxserver/radarr:5.8.3
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:radarr"
    volumes:
      - /mnt/nfs/docker/radarr/config:/config
      - /mnt/nfs/data:/data
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/radarr.conf"
  vars:
    domain: "{{ 'radarr.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'radarr.comprofix.xyz' }}"
    port: 7878
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx
