---
- name: Set Facts
  set_fact:
    container_name: 'radarr'
    
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: radarr
    image: linuxserver/radarr:5.7.0
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:radarr"
    volumes:
      - /mnt/nfs/docker/radarr/config:/config
      - /mnt/nfs/data:/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: radarr.comprofix.xyz
    port: 7878
    protocol: http
  notify: 
    - reload nginx