---
- name: Set Facts
  set_fact:
    container_name: 'readarr'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: readarr
    image: ghcr.io/linuxserver/readarr:develop@sha256:b8aa94ea98b0caf90f94e4bd0f84a5631e3dfcb4b10c927d4516843b95285985
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:readarr"
    volumes:
      - /mnt/nfs/docker/readarr/config/:/config
      - /mnt/nfs/data/:/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: readarr.comprofix.xyz
    port: 8787
    protocol: http
  notify: 
    - reload nginx