---
- name: Set Facts
  set_fact:
    container_name: 'readarr'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: readarr
    image: ghcr.io/linuxserver/readarr:develop@sha256:f33dcc28041ac08bf0ab5f1694cc7ef5a22aa14b68878da38258cffa641087c7
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:readarr"
    volumes:
      - /mnt/nfs/docker/readarr/config/:/config
      - /mnt/nfs/data/:/data
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare
