---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/readarr"
    - "/mnt/nfs/docker/readarr/config"
  
- name: Create the readarr container
  docker_container:
    name: readarr
    image: ghcr.io/linuxserver/readarr:develop@sha256:37e136c638dfa87869ff61876e5e165e8d93887dd1f6c0503582983029b37598
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:readarr"
    volumes:
      - /mnt/nfs/docker/readarr/config/:/config
      - /mnt/nfs/data/:/data
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/readarr.conf"
  vars:
    domain: "{{ 'readarr.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'readarr.comprofix.xyz' }}"
    port: 8787
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx
