---
- name: Set Facts
  set_fact:
    container_name: 'sabnzbd'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: sabnzbd
    image: linuxserver/sabnzbd:4.3.2
    restart_policy: never
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      HOSTNAME: "sabnzbd.comprofix.xyz"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:sabnzbd"
    volumes:
      - /mnt/nfs/docker/sabnzbd/config:/config
      - /mnt/nfs/data:/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: sabnzbd.comprofix.xyz
    port: 8080
    protocol: http
  notify: 
    - reload nginx