---
- name: Set Facts
  set_fact:
    container_name: 'sonarr'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: sonarr
    image: linuxserver/sonarr:4.0.5
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:sonarr"
    volumes:
      - /mnt/nfs/docker/sonarr/config/:/config
      - /mnt/nfs/data:/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: sonarr.comprofix.xyz
    port: 8989
    protocol: http
  notify: 
    - reload nginx