---
- name: Set Facts
  set_fact:
    container_name: 'speedtest'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"

- name: Create the {{container_name}} container
  docker_container:
    name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:0.20.7
    restart_policy: never
    recreate: true
    networks:
      - name: proxy_network
    env:
      APP_KEY: "base64:ViJcK7rSIwGC+TAW7pRWnczB43zPPVHH2Hx80t7eVm0="
      PUID: "1000"
      PGID: "1000"
      DB_CONNECTION: "mysql"
      DB_HOST: "{{ MYSQL_HOST }}"
      DB_PORT: "3306"
      DB_DATABASE: "{{ST_DATABASE}}"
      DB_USERNAME: "{{ST_DB_USERNAME}}"
      DB_PASSWORD: "{{ST_DB_PASSWORD}}"
      TZ: "Australia/Brisbane"
    volumes:
      - /mnt/nfs/docker/speedtest/config:/config
      - /mnt/nfs/docker/speedtest/web:/etc/ssl/web

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: speedtest.comprofix.xyz
    port: 80
    protocol: http
  notify: 
    - reload nginx