---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/speedtest"
    - "/mnt/nfs/docker/speedtest/config"

- name: Create the speedtest container
  docker_container:
    name: speedtest
    image: lscr.io/linuxserver/speedtest-tracker:0.20.7
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      APP_KEY: "base64:ViJcK7rSIwGC+TAW7pRWnczB43zPPVHH2Hx80t7eVm0="
      PUID: "1000"
      PGID: "1000"
      DB_CONNECTION: "mysql"
      DB_HOST: "{{ MYSQL_HOST }}"
      DB_PORT: "3306"
      DB_DATABASE: "{{ST_DATABASE}}"
      DB_USERNAME: "{{ST_DB_USERNAME}}"
      DB_PASSWORD: "{{ST_DB_PASSWORD}}"
      TZ: "Australia/Brisbane"
    volumes:
      - /mnt/nfs/docker/speedtest/config:/config
      - /mnt/nfs/docker/speedtest/web:/etc/ssl/web
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/speedtest.conf"
  vars:
    domain: "{{ 'speedtest.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'speedtest.comprofix.xyz' }}"
    port: 80
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx
