---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/stirlingpdf"
    - "/mnt/nfs/docker/stirlingpdf/config"

- name: Download tessdata
  git:
    repo: https://github.com/tesseract-ocr/tessdata.git
    dest: "/opt/tessdata"
    clone: yes
    update: yes
    force: yes

- name: Create the stirlingpdf container
  docker_container:
    name: stirlingpdf
    image: ghcr.io/stirling-tools/s-pdf:0.26.1
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
    volumes:
      - /opt/tessdata:/usr/share/tessdata #Required for extra OCR languages
      - /mnt/nfs/docker/stirlingpdf/configs:/configs  
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/stirlingpdf.conf"
  vars:
    domain: "{{ 'stirlingpdf.dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'stirlingpdf.comprofix.xyz' }}"
    port: 8080
    protocol: http
    cert: "{{ 'dev.comprofix.xyz' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.xyz' }}"
  notify: 
    - reload nginx

