---
- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/vaultwarden"
    - "/mnt/nfs/docker/vaultwarden/config"
  
- name: Create the vaultwarden container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:1.31.0
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    volumes:
      /mnt/nfs/docker/vaultwarden/data:/data
  register: container

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.xyz.j2
    dest: "/mnt/nfs/docker/nginx/config/planka.conf"
  vars:
    domain: "{{ 'vault.dev.comprofix.com' if inventory_hostname == 'dev.comprofix.xyz' else 'vault.comprofix.com' }}"
    port: 80
    protocol: http
    cert: "{{ 'dev.comprofix.com' if inventory_hostname == 'dev.comprofix.xyz' else 'comprofix.com' }}"
  notify: 
    - reload nginx
