---
- name: Set Facts
  set_fact:
    container_name: 'vaultwarden'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: vaultwarden
    image: vaultwarden/server:1.30.5
    restart_policy: always
    recreate: true
    networks:
      - name: proxy_network
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
    volumes:
      /mnt/nfs/docker/vaultwarden/data:/data

- name: Setup reverse proxy
  template:
    src: templates/nginx/comprofix.com.j2
    dest: "/mnt/nfs/docker/nginx/config/{{container_name}}.conf"
  vars:
    domain: vault.comprofix.com
    port: 80
    protocol: http

- name: Restart nginx
  community.docker.docker_container_exec:
    container: nginx
    command: nginx -s reload