---
ansible_user: administrator

docker_configs: "/mnt/nfs/docker" # CHANGE_ME!!! - Change to the folder where you docker volume data lives.

# Proxmox API variables
api_host: "{{ ansible_host }}" 
api_user: root@pam # CHANGE_ME!!!
api_password: change_me # CHANGE_ME!!! - Set login password
api_token_id: ansible 
api_token_secret: change_me # CHANGE_ME!!! - Set Tocken Secret.

# Proxmox node target
node_target: pve

# VM storage target
storage_target: local-zfs # CHANGE_ME!!! - Set storage target name

# cloud-init configuration
ci_user: administrator # CHANGE_ME!!! - Set Cloud-init username
ci_password: change_me