---
- name: Set Facts
  set_fact:
    container_name: 'lidarr'

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ docker_configs }}/{{container_name}}"
    - "{{ docker_configs }}/{{container_name}}/config"
  
- name: Create the {{container_name}} container
  docker_container:
    name: lidarr
    image: ghcr.io/linuxserver/lidarr:latest@sha256:2e39f5a1a1c12d168dbc59bf535e4b621210cba7eb39c44fabc7288c2c1ddc1c
    restart_policy: always
    recreate: true
    networks:
      - name: traefik
    env:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Brisbane"
      AUTO_UPDATE: "true" #optional
      DOCKER_MODS: "ghcr.io/themepark-dev/theme.park:lidarr"
    volumes:
      - /dockerdata/lidarr/config:/config
      - /mnt/nfs/data:/data
    labels:
      traefik.enable=true
      traefik.http.routers.{{container_name}}.rule=Host(`{{container_name}}.{{traefik_domain}}`)
      traefik.http.routers.{{container_name}}.entrypoints=https
      traefik.http.routers.{{container_name}}.tls.certresolver=cloudflare
