---
- name: Removed old configs - containers should supply fresh configs.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/mnt/nfs/docker/nginx"

- name: Create config folders
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/mnt/nfs/docker/nginx"
    - "/mnt/nfs/docker/nginx/config"

- name: Create proxy docker network
  docker_network:
    name: "proxy_network"
    state: present

- name: Create the nginx container
  docker_container:
    name: nginx
    image: nginx:1.27
    restart_policy: no
    recreate: true
    networks:
      - name: proxy_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/nfs/docker/nginx/config:/etc/nginx/conf.d/
      - /etc/letsencrypt:/etc/letsencrypt
    