---
- hosts: all
  become: yes
  roles:
    - base
  tags: base_install

- hosts: gitea
  become: yes
  roles:
    - base
    - role: certbot    
      certificates:
        - name: gitea.comprofix.com
    - role: gitea
  tags: gitea_install

- hosts: containers
  become: yes
  roles:
    - docker
    - role: nfs
      mounts:
      - name: Docker share
        path: /mnt/nfs/docker
        src: truenas.comprofix.xyz:/mnt/datapool/docker
      - name: Data share
        path: /mnt/nfs/data
        src: truenas.comprofix.xyz:/mnt/datapool/data
    - nginx
    - role: certbot
      certificates:
      - name: 'comprofix.com'
      - name: 'comprofix.xyz' 
    - containers
  tags: containers_install
    
- hosts: omada
  become: yes
  roles:
    - base
    - docker
    - nginx
    - role: certbot
      certificates:
      - name: 'omada.comprofix.xyz'
    - omada
  tags: omada_install

- hosts: jellyfin
  become: yes
  roles:
    - base
    - role: nfs
      mounts:
      - name: Data share
        path: /mnt/nfs/data
        src: truenas.comprofix.xyz:/mnt/datapool/data
    - docker
    - nginx
    - role: certbot
      certificates:
      - name: 'jellyfin.comprofix.xyz'
    - jellyfin
  tags: jellyfin_install





  

