---
- hosts: containers
  become: yes
  roles:
    - base
    - docker
    - role: nfs
      mounts:
      - name: Docker share
        path: /mnt/nfs/docker
        src: truenas.comprofix.xyz:/mnt/datapool/docker
      - name: Data share
        path: /mnt/nfs/data
        src: truenas.comprofix.xyz:/mnt/datapool/data
    - role: certbot
      certificates:
      - name: 'comprofix.com'
      - name: 'comprofix.xyz' 
    - containers
    - nginx
  tags: containers_install






  

