---
- hosts: all
  become: yes
  roles:
    - base
  tags: base_install

- hosts: nfs
  become: yes
  roles:
    - base
    - nfs
  tags: nfs_install

- hosts: docker
  become: yes
  roles:
    - base
    - docker
  tags: docker_install

- hosts: gitea
  become: yes
  roles:
    - base
    - role: certbot    
      certificates:
        - name: gitea.comprofix.com
    - role: gitea
  tags: gitea_install

- hosts: containers
  become: yes
  roles:
    - containers
  tags: containers_install

    
# - hosts: omada
#   become: yes

#   tasks: 
#     - name: Deploy Omada
#       import_tasks: tasks/omada.yml
#       tags: omada_install

