---
- hosts: jellyfin
  become: yes
  roles:
    - base
    - role: nfs
      mounts:
      - name: Data share
        path: /mnt/nfs/data
        src: truenas.comprofix.xyz:/mnt/datapool/data
    - docker
    - role: certbot
      certificates:
      - name: 'jellyfin.comprofix.xyz'
    - nginx
    - jellyfin
  tags: jellyfin_install