---
- hosts: all
  become: yes
  roles:
    - role: base
  tags: base

      

- hosts: nfs
  become: yes
  roles:
    - role: nfs
      nfs_share_mounts:
        - name: Docker share
          path: /mnt/nfs/docker
          src: truenas.comprofix.xyz:/mnt/DS4232/docker
        - name: Data share
          path: /mnt/nfs/data
          src: truenas.comprofix.xyz:/mnt/DS4232/data
  tags: nfs

- hosts: docker
  become: yes
  roles:
    - role: docker
  tags: docker
    
  
- hosts: containers
  become: yes
  roles:
    - role: containers
  tags: containers

    
# - hosts: omada
#   become: yes

#   tasks: 
#     - name: Deploy Omada
#       import_tasks: tasks/omada.yml
#       tags: omada_install

