---
- hosts: all
  become: yes
  roles:
    - role: base
  tags: base_install

- hosts: nfs
  become: yes
  roles:
    - role: nfs
  tags: nfs_install

- hosts: docker
  become: yes
  roles:
    - role: docker
  tags: docker_install

- hosts: gitea
  become: yes
  roles:
    - role: certbot
      certificates:
        - name: gitea.comprofix.com
  tags: gitea_install

- hosts: containers
  become: yes
  roles:
    - role: containers
  tags: containers_install

    
# - hosts: omada
#   become: yes

#   tasks: 
#     - name: Deploy Omada
#       import_tasks: tasks/omada.yml
#       tags: omada_install

