---
- hosts: all
  become: yes
  roles:
    - base
  tags: base_install

- hosts: nfs
  become: yes
  roles:
    - base
    - nfs
  tags: nfs_install

- hosts: docker
  become: yes
  roles:
    - base
    - docker
  tags: docker_install

- hosts: gitea
  become: yes
  roles:
    - base
    - role: certbot    
      certificates:
        - name: gitea.comprofix.com
    - role: gitea
  tags: gitea_install

- hosts: containers
  become: yes
  roles:
    - role: certbot
      certificates:
      - name: '*.comprofix.com'
      - name: '*.comprofix.xyz' 
    - containers
  tags: containers_install

    
- hosts: omada
  become: yes
  roles:
    - base
    - docker
    - omada
  tags: omada_install

- hosts: dev
  become: yes
  roles:
    - base
    - docker
    - role: certbot
      certificates:
      - name: '*.comprofix.com'
      - name: '*.comprofix.xyz' 
  tags: dev_install



  

