install_packages: # Add addition packages here
  - vim-nox
  - git
  - zsh
  - curl
  - wget
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - python3
  - python3-pip
  - nfs-common
  - cron
  - jq
  - sudo
  - logwatch
  - sendemail
  - libio-socket-ssl-perl
  - libnet-ssleay-perl
