---
- name: Add gitlab repository
  shell: curl -s https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash

- name: Install gitlab packages
  package:
    name: "gitlab-ce"
    state: "present"

- name: reconfiguring gitlab-ce (first-time)
  command: gitlab-ctl reconfigure
  args:
    creates: /var/opt/gitlab/bootstrapped
  failed_when: false
  notify: restart gitlab

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/gitlab/ssl
    state: directory
    mode: '0755'

- name: Create Certificate links (1/4)
  file:
    src: "/etc/letsencrypt/live/registry.git.comprofix.com/fullchain.pem"
    dest: "/etc/gitlab/ssl/registry.git.comprofix.com.crt"
    state: link

- name: Create Certificate links (2/4)
  file:
    src: "/etc/letsencrypt/live/registry.git.comprofix.com/privkey.pem"
    dest: "/etc/gitlab/ssl/registry.git.comprofix.com.key"
    state: link

- name: Create Certificate links (3/4)
  file:
    src: "/etc/letsencrypt/live/git.comprofix.com/fullchain.pem"
    dest: "/etc/gitlab/ssl/git.comprofix.com.crt"
    state: link

- name: Create Certificate links (4/4)
  file:
    src: "/etc/letsencrypt/live/git.comprofix.com/privkey.pem"
    dest: "/etc/gitlab/ssl/git.comprofix.com.key"
    state: link

- name: configuring gitlab-ce
  template:
    src: "templates/gitlab.rb.j2"
    dest: "/etc/gitlab/gitlab.rb"
    owner: root
    group: root
    mode: 0600
  notify:
    - reconfigure gitlab
    - restart gitlab

