---
- name: Install Certbot
  package: 
    name:
      - certbot
      - python3-certbot-dns-cloudflare
    state: present
  become: yes

- name: Install openssl python package
  ansible.builtin.pip:
    name: pyopenssl

- name: Copy Cloudflare credentials
  template:
    src: templates/cloudflare.ini
    dest: "/etc/letsencrypt/cloudflare.ini"
    mode: '0600'

- name: Check Certificates exist
  stat:
    path: "/etc/letsencrypt/live/{{item.name}}"
  with_items: "{{ certificates }}"
  register: folder_check_results
  ignore_errors: True


- name: Generate certificates
  command: certbot certonly --noninteractive --agree-tos --email "{{ CF_API_EMAIL }}" --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare.ini -d '{{ item.item.name }}' -d '*.{{ item.item.name }}'
  become: yes
  with_items: "{{ folder_check_results.results }}"
  when: item.stat.exists == False

- name: Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew --quiet"
    minute: "30"
    hour: "3"
    user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

- name: Fix ownership for certificats
  file: 
    path: /etc/letsencrypt/live
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX

- name: Fix ownership for certificats
  file: 
    path: /etc/letsencrypt/archive
    owner: root
    group: root
    mode: u=rwX,g=rX,o=rX